# .github/workflows/build.yml
name: Build Next.js App

on:
    workflow_call: # Makes this Workflow/Job reusable from other workflow

jobs:
    build:
        name: Build Next.js App
        runs-on: ubuntu-latest
        timeout-minutes: 6

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Set up Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: 18
                  cache: 'npm'

            - name: Cache Next.js build cache
              uses: actions/cache@v4
              with:
                  path: .next/cache
                  key: ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-${{ hashFiles('**.[jt]s', '**.[jt]sx') }}
                  restore-keys: |
                      ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-

            - name: Install dependencies
              run: npm ci

            - name: Build project
              run: npm run build
