# .github/workflows/build.yml
name: Build Next.js App

on:
    workflow_run:
        workflows: ['Lint & Type Check']
        types:
            - completed

concurrency:
    group: build-${{ github.ref }}
    cancel-in-progress: true

jobs:
    build:
        name: Build Next.js App
        runs-on: ubuntu-latest
        timeout-minutes: 6
        if: ${{ github.event.workflow_run.conclusion == 'success' }}

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Set up Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: 18
                  cache: 'npm'

            - name: Cache Next.js build cache
              uses: actions/cache@v4
              with:
                  path: .next/cache
                  key: ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-${{ hashFiles('**.[jt]s', '**.[jt]sx') }}
                  restore-keys: |
                      ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-

            - name: Install dependencies
              run: npm ci

            - name: Build project
              run: npm run build
