# .github/workflows/deploy.yml
name: Deploy to Vercel

on:
    workflow_call: # Makes this Workflow/Job reusable from other workflow

jobs:
    deploy:
        name: Deploy to Vercel via Vercel-CLI
        runs-on: ubuntu-latest
        timeout-minutes: 3
        # Only deploy on pushes & PR merges to 'main' && Only If it's Prev. workflow Succeeded &&  Ignore auto-push from bots....
        if: github.ref == 'refs/heads/main' && !contains(github.actor, 'vercel') && !contains(github.actor, 'dependabot[bot]') && !contains(github.actor, 'github-actions[bot]')

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Setup Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: 18

            - name: Deploy to Vercel via Vercel-CLI
              run: npx vercel --prod --token=$VERCEL_TOKEN --scope=$VERCEL_ORG_ID --confirm --yes
              env:
                  VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
                  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
                  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
