# deploy.yml
name: Portfolio Deploy

on:
    workflow_run:
        workflows: ['Portfolio CI'] # must match the name in ci.yml
        types: [completed]

jobs:
    deploy:
        if: ${{ github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.head_branch == 'main' }}
        runs-on: ubuntu-latest

        steps:
            - name: Trigger Vercel Deployment
              run: curl -X POST "${{ secrets.VERCEL_DEPLOY_HOOK }}"
